spring:
  profiles.active: dev
  application:
    # Determines the configs to grab from spring cloud server
    name: vocabulary-api
  cloud:
    config:
      uri: https://localhost:8888
      profile: ${spring.profiles.active}
      label: develop
      #fail-fast: true
      client:
        ssl:
          trust-store: config/keystore/vocabulary-api.p12
          trust-store-password: aaron456
          trust-store-type: PKCS12
  config:
    import: configserver:${spring.cloud.config.uri}

message:
  resource:
    basename: ${spring.cloud.config.uri}/${spring.application.name}/default/${spring.cloud.config.label}/resourcebundle/messages

logging:
  config: ${spring.cloud.config.uri}/${spring.application.name}/default/${spring.cloud.config.label}/logback.xml